name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  ssh-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Pull latest code on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /opt/app/app_birthday/src && git pull origin main"

    - name: Build and restart Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          cd /opt/app/app_birthday/src &&
          docker build -t app_birthday . &&
          docker rm -f app_birthday || true &&
          docker run -d --name app_birthday --restart unless-stopped app_birthday      
        "